---
- name: Get AWS Account Details
  hosts: localhost
  connection: local
  vars:
    aws_region: "{{ lookup('env', 'AWS_REGION') | default('us-east-1') }}"
  tasks:
    - name: Gather AWS Account Details
      amazon.aws.aws_caller_info:
        aws_region: "{{ aws_region }}"
      register: aws_account_info

    - name: Display AWS Account Details
      debug:
        msg:
          - "AWS Account ID: {{ aws_account_info.account }}"
          - "AWS User ID: {{ aws_account_info.user_id }}"
          - "AWS ARN: {{ aws_account_info.arn }}"
